services:
  tbmedia:
    image: ghcr.io/vinip1250-art/tbmedia:latest
    container_name: tbmedia
    restart: unless-stopped
    networks:
      - npm-net
    environment:
      - PORT=7860
      - CACHE_TTL_CATALOG=180
      - CACHE_TTL_STREAM=21600
      - REDIS_URL=redis://redis:6379/6
      - REDIS_TLS=false
      - ADMIN_SECRET=fwCYQB3kumSA6nICF22uxviB
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7860/"]
      interval: 30s
      timeout: 5s
      retries: 3
